SET NAMES utf8mb4;

CREATE TABLE `revenue_targets` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `period_type` VARCHAR(20) NOT NULL COMMENT 'MONTHLY | QUARTERLY | YEARLY',
    `period_key` VARCHAR(10) NOT NULL COMMENT 'YYYY-MM | YYYY-QN | YYYY',
    `period_start` DATE NOT NULL,
    `period_end` DATE NOT NULL,
    `dept_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '0 = company-wide, >0 = specific department',
    `target_type` VARCHAR(30) NOT NULL DEFAULT 'TOTAL' COMMENT 'TOTAL | NEW_CONTRACT | RENEWAL | RECURRING',
    `target_amount` DECIMAL(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Target revenue',
    `actual_amount` DECIMAL(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Actual revenue (snapshot)',
    `notes` TEXT NULL,
    `approved_by` BIGINT UNSIGNED DEFAULT NULL,
    `approved_at` TIMESTAMP NULL DEFAULT NULL,
    `data_scope` VARCHAR(50) DEFAULT NULL,
    `created_by` BIGINT UNSIGNED DEFAULT NULL,
    `updated_by` BIGINT UNSIGNED DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_target_period_dept_type` (`period_type`, `period_key`, `dept_id`, `target_type`),
    KEY `idx_rt_period` (`period_type`, `period_key`),
    KEY `idx_rt_dept` (`dept_id`),
    KEY `idx_rt_active` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `revenue_snapshots` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `period_type` VARCHAR(20) NOT NULL COMMENT 'MONTHLY | QUARTERLY | YEARLY',
    `period_key` VARCHAR(10) NOT NULL COMMENT 'YYYY-MM | YYYY-QN | YYYY',
    `dimension_type` VARCHAR(30) NOT NULL DEFAULT 'COMPANY' COMMENT 'COMPANY | DEPARTMENT | CUSTOMER | PRODUCT',
    `dimension_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '0 when dimension=COMPANY',
    `dimension_label` VARCHAR(255) DEFAULT NULL COMMENT 'Denormalized: dept/customer/product name',
    `contract_expected` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `contract_collected` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `contract_outstanding` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `contract_count` INT UNSIGNED NOT NULL DEFAULT '0',
    `invoice_issued` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `invoice_collected` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `invoice_outstanding` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `invoice_count` INT UNSIGNED NOT NULL DEFAULT '0',
    `total_expected` DECIMAL(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Reconciled expected',
    `total_collected` DECIMAL(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Reconciled collected',
    `total_outstanding` DECIMAL(18,2) NOT NULL DEFAULT '0.00' COMMENT 'Reconciled outstanding',
    `target_amount` DECIMAL(18,2) NOT NULL DEFAULT '0.00',
    `achievement_pct` DECIMAL(5,1) NOT NULL DEFAULT '0.0',
    `snapshot_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_snapshot_period_dimension` (`period_type`, `period_key`, `dimension_type`, `dimension_id`),
    KEY `idx_rs_period` (`period_type`, `period_key`),
    KEY `idx_rs_dimension` (`dimension_type`, `dimension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
