-- ================================================================================
-- SCRIPT IMPORT 197 YÊU CẦU VÀO BẢNG CUSTOMER_REQUEST_CASES
-- Ngày: 2026-04-02
-- Nguồn: plan-code/Dieu_chinh_ql_yc_khach_hang/du-lieu-can-import/danh sách yêu cầu.xlsx
-- Trạng thái: new_intake (Mới tiếp nhận)
-- ================================================================================
--
-- CÁCH CHẠY ĐÚNG (với UTF-8 encoding):
-- mysql -h localhost -u root -proot vnpt_business_db --default-character-set=utf8mb4 < 2026-04-02_02_insert_requests.sql
-- ================================================================================

-- SET encoding UTF-8
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

--
-- REFERENCE DATA:
-- ================
-- workflow_definition_id = 4 (LUONG_A - Luồng xử lý Yêu cầu khách hàng)
--
-- SUPPORT SERVICE GROUPS:
--   1 = HIS L2
--   2 = HIS L3
--   5 = HOÀN THIỆN PHẦN MỀM
--   6 = Hiss Bệnh Viện Sản Nhi
--
-- INTERNAL USERS (receivers):
--  10 = Phạm Thanh Trào (traopt.hgi)
--  32 = Phan Phú Thịnh (thinhpp.cto)
--  36 = Lê Đào Thiên Đức (ducldt.cto)
--  39 = Nguyễn Hải Đăng (dangnh.hgi)
--  42 = Trương Công Quốc Huy (huytcq.cto)
--  43 = Nguyễn Vĩnh Lạp (lapnv.hgi)
--  45 = Võ Hoàng Kiệt (kietvh.cto)
--  46 = Dương Tố Như (nhudt.cto)
--  50 = Nguyễn Nhựt Trường (truongnn.cto)
--
-- CUSTOMERS (customer_code -> id):
--   93003 -> 7  (TTYT KV Long Mỹ)
--   93004 -> 8  (TTYT KV Phụng Hiệp)
--   93005 -> 12 (TTYT KV Châu Thành)
--   93007 -> 3  (BV Sản - Nhi Hậu Giang)
--   93015 -> 97 (Trạm Y tế Hỏa Lựu)
--   93016 -> 14 (BVĐK KV Ngã Bảy)
--   93999 -> (tạo mới cho BV Ung bướu Cần Thơ)
-- ================================================================================

-- Tạo customers mới nếu chưa tồn tại
INSERT IGNORE INTO `customers` (`customer_code`, `customer_name`, `created_by`, `created_at`, `updated_at`)
VALUES
    ('93999', 'Bệnh viện Ung bướu Cần Thơ', 9, NOW(), NOW());

-- INSERT 197 yêu cầu
-- Lưu ý: customer_id dùng subquery theo customer_code để tránh hardcode ID
INSERT INTO `customer_request_cases`
(`request_code`, `customer_id`, `customer_personnel_id`, `project_id`, `product_id`,
 `support_service_group_id`, `summary`, `description`, `priority`, `source_channel`,
 `workflow_definition_id`, `current_status_code`,
 `received_by_user_id`, `created_by`, `updated_by`, `created_at`, `updated_at`)
VALUES
-- STT 1-10
('CRC-202604-0001', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'In phiếu dinh dưỡng không được BN: Nguyễn Huỳnh Gia Phú', 'Bệnh viện Ung bướu Cần Thơ - Yêu cầu in phiếu dinh dưỡng', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0002', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'Bổ sung tính năng theo phiếu yêu cầu', 'BV Sản Nhi - Bổ sung tính năng', 2, 'Kênh khác', 1, 'new_intake', 50, 9, 9, NOW(), NOW()),
('CRC-202604-0003', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Yêu cầu của Phòng Kế hoạch', 'BVĐK KV Ngã Bảy - Yêu cầu phòng kế hoạch', 2, 'Kênh khác', 1, 'new_intake', 32, 9, 9, NOW(), NOW()),
('CRC-202604-0004', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Yêu cầu đơn vị khẩn trương rà soát, nâng cấp và hoàn thiện hệ thống phần mềm quản lý bệnh viện để đáp ứng đầy đủ việc tạo lập, ký số, chuẩn hóa và liên thông dữ liệu Sổ sức khỏe điện tử tích hợp trên ứng dụng VNeID theo Quyết định của BYT; bảo đảm liên thông dữ liệu cho 100% người bệnh từ ngày 01/01/2026, đầy đủ các nhóm thông tin hành chính, tiền sử, thông tin từng đợt khám chữa bệnh và tóm tắt hồ sơ bệnh án; đồng thời bảo đảm an toàn, bảo mật dữ liệu cá nhân, phục vụ việc khai thác, sử dụng dữ liệu VNeID thay thế hồ sơ giấy trong khám chữa bệnh và giải quyết thủ tục hành chính theo quy định.', 'BVĐK KV Ngã Bảy - Yêu cầu liên thông VNeID', 2, 'Kênh khác', 1, 'new_intake', 46, 9, 9, NOW(), NOW()),
('CRC-202604-0005', NULL, NULL, NULL, NULL, 2, 'Tách hoặc tắt chẩn đoán YHCT ra khỏi ICD-10. Có 1 vài ca bệnh có chẩn đoán YHCT lẫn vào ICD-10 (lên cổng sẽ bị trả về). Bên PK không có khám YHCT', 'Phòng khám Nhơn Ái - Tách chẩn đoán YHCT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0006', NULL, NULL, NULL, NULL, 2, 'Khi in Bệnh án chi tiết. Mục 5. Tóm tắt triệu chứng và hội chứng bản in chỉ thể hiện được 4 dòng. Không in được hết nội dung của mục 5', 'Bệnh viện Tâm Thần Cần Thơ - In bệnh án chi tiết', 2, 'Kênh khác', 1, 'new_intake', 50, 9, 9, NOW(), NOW()),
('CRC-202604-0007', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'NHỜ VNPT XEM DÙM PHÒNG VTYT, CÔNG THỨC TÍNH BỊ SAI LỆCH', 'Bệnh viện Ung bướu Cần Thơ - Công thức tính sai', 2, 'Kênh khác', 1, 'new_intake', 50, 9, 9, NOW(), NOW()),
('CRC-202604-0008', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'Thêm giờ vào mục ngày xuất trong menu bán thuốc tại quầy', 'BV Sản Nhi - Thêm giờ ngày xuất', 2, 'Kênh khác', 1, 'new_intake', 42, 9, 9, NOW(), NOW()),
('CRC-202604-0009', NULL, NULL, NULL, NULL, 2, 'Dạ em gửi a/c VNPT một số yêu cầu của bác Thái nhờ a/c hỗ trợ điều chỉnh cho viện giúp ạ', 'PK Hòa Hảo Long Mỹ - Yêu cầu điều chỉnh', 2, 'Kênh khác', 1, 'new_intake', 36, 9, 9, NOW(), NOW()),
('CRC-202604-0010', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Tôi làm theo hướng dẫn thì thấy phần chẩn đoán cơ bản đủ, giống nhau giữa 2 toa. nhưng khi tôi chưa thấy tính năng hủy ký số toa thuốc, nhờ bên mình xem lại dùm, do không hủy ký số được nên khi xóa toa phải xóa từng thuốc. Với trên toa này có lấy luôn phần diễn biến bệnh của bệnh nhân nên làm cho toa thuốc dài, với không đúng mấu của thông tư 26.', 'TTYT KV Long Mỹ - Hủy ký số toa thuốc', 2, 'Kênh khác', 1, 'new_intake', 32, 9, 9, NOW(), NOW()),
-- STT 11-20
('CRC-202604-0011', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, '#donvi: 93003 - #hotro: Ngoại trú - CHUNG CHÍ TÀI - 24/2 - phòng 15 ký số phiếu PHIẾU CHỈ ĐỊNH PTTT NGOẠI TRÚ bị lỗi. Kiểm thử: Sau khi đổi tên DV khâu vết thương đơn giản vùng đầu mặt cổ bỏ dấu < thành khâu vết thương đơn giản vùng đầu mặt cổ chiều dài l0 cm thì mới ký số thành công', 'TTYT KV Long Mỹ - Lỗi ký số phiếu PTTT', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0012', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, '#donvi: 93016 - điều chỉnh mẫu Bệnh án ngoại trú. BN: TRẦN THANH TRANG - khoa lọc thận. Link: /cmu_funs_emr_benhanngoaitru_yhct', 'BVĐK KV Ngã Bảy - Điều chỉnh mẫu bệnh án ngoại trú', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0013', (SELECT id FROM customers WHERE customer_code = '93015'), NULL, NULL, NULL, 2, '#donvi: 93015 - Hỏa Lựu - #hotro: Nhờ thêm cột Thành tiền phía sau cột Đơn giá trong Biên Bản Kiểm Kê Kho (Thành tiền = Số lượng Sổ sách * Đơn giá)', 'Trạm Y tế Hỏa Lựu - Thêm cột thành tiền', 2, 'Kênh khác', 1, 'new_intake', 45, 9, 9, NOW(), NOW()),
('CRC-202604-0014', (SELECT id FROM customers WHERE customer_code = '93005'), NULL, NULL, NULL, 2, 'Sắp xếp thứ tự ưu tiên để Bác sỹ dễ thấy và xử lý: 1. ký checkin, 2. ký XML 4750, 3. Ký XML giấy ốm, 4. ký MXL giấy ra viện hưởng chế độ... Thứ hai: Đối với các trường hợp có chỉ định CLS. Nếu chưa có kết quả thì không cấp thuốc được nhé. Trường hợp này cổng đã bắt', 'TTYT KV Châu Thành - Sắp xếp ưu tiên ký số', 2, 'Kênh khác', 1, 'new_intake', 50, 9, 9, NOW(), NOW()),
('CRC-202604-0015', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Cập nhật tự động Buồng, Giường phiếu phẫu thuật, thủ thuật theo thông tin hành chính và không có trường nhập, Số vào viện không cập nhật theo bệnh án (Phiếu phẫu thuật, thủ thuật), Bác sĩ phẫu thuật/ thủ thuật nếu có điều dưỡng hỗ trợ thì sẽ điền vào chỗ nào', 'TTYT KV Long Mỹ - Cập nhật phiếu phẫu thuật', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0016', (SELECT id FROM customers WHERE customer_code = '93004'), NULL, NULL, NULL, 2, 'Mẫu siêu âm tuyến giáp bị qua 2 trang giấy, mới bị hôm nay (05/03/2026). Phiếu trả kết quả cls (Phiếu siêu âm) phần chữ ký nhảy sang trang 2', 'TTYT KV Phụng Hiệp - Mẫu siêu âm 2 trang', 2, 'Kênh khác', 1, 'new_intake', 50, 9, 9, NOW(), NOW()),
('CRC-202604-0017', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Sau khi hạn của BHYT vừa hết thì khi chỉ định ở bất kì dịch vụ nào cũng sẽ có cảnh báo đã hết hạn BHYT (dù còn trong thời hạn 15 ngày)', 'Bệnh viện Ung bướu Cần Thơ - Cảnh báo hết hạn BHYT', 2, 'Kênh khác', 1, 'new_intake', 46, 9, 9, NOW(), NOW()),
('CRC-202604-0018', NULL, NULL, NULL, NULL, 2, 'Nhờ a/c phụ trách ký số VNPT và PM Lis kết hợp cấu hình ký số trả kết quả trên LIS giúp viện ạ', 'PK Hòa Hảo Long Mỹ - Cấu hình ký số LIS', 2, 'Kênh khác', 1, 'new_intake', 42, 9, 9, NOW(), NOW()),
('CRC-202604-0019', NULL, NULL, NULL, NULL, 2, 'mẫu xuất trên PM đang thiếu so với mẫu gửi báo cáo. KH nhắn: 2 mẫu này e xuất từ phần mềm kcb nó ko đủ các trường giống như 2 mẫu sổ trên e nhờ hỗ trợ ạ. Dạ nhờ các anh hỗ trợ sớm giúp e ạ. Vì phải bắt đầu báo của tháng 1/2026', 'TTYT KV Vị Thủy - Mẫu xuất thiếu trường', 2, 'Kênh khác', 1, 'new_intake', 46, 9, 9, NOW(), NOW()),
('CRC-202604-0020', (SELECT id FROM customers WHERE customer_code = '93005'), NULL, NULL, NULL, 2, 'Phiếu Điện Tim ở phần kết luận in bị thiếu dòng', 'TTYT KV Châu Thành - Phiếu điện tim thiếu dòng', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
-- STT 21-30
('CRC-202604-0021', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Giấy ra viện - Mục giám đốc ủy quyền thêm các bác sĩ trong danh sách excel', 'BVĐK KV Ngã Bảy - Giấy ra viện ủy quyền', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0022', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Yêu cầu của Phòng KHNV', 'TTYT KV Long Mỹ - Yêu cầu phòng KHNV', 2, 'Kênh khác', 1, 'new_intake', 45, 9, 9, NOW(), NOW()),
('CRC-202604-0023', (SELECT id FROM customers WHERE customer_code = '93004'), NULL, NULL, NULL, 2, 'Tân Phước Hưng xin hỗ trợ thêm dùm danh mục thuốc vào phần mềm', 'TTYT KV Phụng Hiệp - Danh mục thuốc', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0024', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Chỉnh lại vị trí ký số trong phần Bác sỹ gây mê ở Phiếu Giấy cam đoan chấp thuận phẫu thuật, thủ thuật và gây mê hồi sức. Đường dẫn: Thông tin điều trị --> khác --> 18 - Giấy cam đoan chấp thuận phẫu thuật, thủ thuật và gây mê hồi sức', 'BVĐK KV Ngã Bảy - Ký số phiếu gây mê', 2, 'Kênh khác', 1, 'new_intake', 46, 9, 9, NOW(), NOW()),
('CRC-202604-0025', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Bổ sung nút lệnh copy phiếu theo dõi lọc máu. Bệnh án: Bệnh án Ngoại trú', 'TTYT KV Long Mỹ - Copy phiếu lọc máu', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0026', NULL, NULL, NULL, NULL, 2, 'bổ sung xét nghiệm', 'Phòng Khám Tâm Phúc Cần Thơ - Bổ sung xét nghiệm', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0027', NULL, NULL, NULL, NULL, 2, 'bổ sung mục tiền công dịch vụ/chích thuốc', 'Phòng Khám Tâm Phúc Cần Thơ - Tiền công dịch vụ', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0028', NULL, NULL, NULL, NULL, 2, 'bổ sung dùm anh thuốc nội bộ', 'Phòng Khám Tâm Phúc Cần Thơ - Thuốc nội bộ', 2, 'Kênh khác', 1, 'new_intake', 39, 9, 9, NOW(), NOW()),
('CRC-202604-0029', NULL, NULL, NULL, NULL, 2, 'xóa thuốc nội trú treo từ năm 2025 và đầu năm 2026', 'BVCK Tâm thần & Da liễu - Xóa thuốc treo', 2, 'Kênh khác', 1, 'new_intake', 42, 9, 9, NOW(), NOW()),
('CRC-202604-0030', NULL, NULL, NULL, NULL, 2, 'Thêm màu đối với các hồ sơ đã ký XML gửi cổng, hiện đang bị trùng màu vàng với các hồ sơ sẵn sàng thanh toán, kg phân biệt được trạng thái hồ sơ', 'Trạm Y tế xã Thạnh An - Màu hồ sơ ký XML', 2, 'Kênh khác', 1, 'new_intake', 45, 9, 9, NOW(), NOW()),
-- STT 31-40
('CRC-202604-0031', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'nhờ anh chị kiểm tra dùm em hiện tại chỗ: Số lưu trữ trên HSBA điện tử đang tự động lấy Số vào viện để điền vào.', 'TTYT KV Long Mỹ - Số lưu trữ HSBA', 2, 'Kênh khác', 1, 'new_intake', 32, 9, 9, NOW(), NOW()),
('CRC-202604-0032', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Hiện nay BV Ngã Bảy thường xuyên phát sinh trường hợp bệnh nhân có BHYT có kê DVKT THU PHÍ. Vì vậy BV đề nghị phần mềm thiết lập chế độ in BẢNG KÊ KHÔNG BHYT đối bệnh nhân ngoại trú CÓ BHYT', 'BVĐK KV Ngã Bảy - In bảng kê không BHYT', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0033', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'nhờ các bạn hỗ trợ, phiếu truyền máu đã ký số người thực hiện XN nhưng không hiển thị. Phan Thị Bích Vân, khoa phụ. Khách hàng mong muốn: Thông tin chăm sóc -> Truyền máu -> Chọn xem phiếu diễn biến', 'BV Sản Nhi - Ký số phiếu truyền máu', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0034', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Vấn đề gửi chứng từ CT07 bị lỗi Không đọc được hồ sơ thứ 1. Bệnh viện đã liên hệ được với group Teca. Sau khi xem dữ liệu xml của hồ sơ, Teca xác định không đúng chuẩn định dạng. PM xem lại nhé', 'BVĐK KV Ngã Bảy - Lỗi gửi CT07', 2, 'Kênh khác', 1, 'new_intake', 43, 9, 9, NOW(), NOW()),
('CRC-202604-0035', NULL, NULL, NULL, NULL, 2, 'Phiếu điều trị diễn tiến thêm SpO2 tiếp theo mạch, nhiệt độ,..', 'BV Lao phổi - Thêm SpO2', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0036', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'Bổ sung ký số cho LIS, RIS trên web và app VNPT HIS', 'BV Sản Nhi - Ký số LIS RIS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0037', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'Dữ liệu xuất nhập tồn lấy theo ngày dự trù (hiện tại lấy theo ngày duyệt phiếu)', 'BV Sản Nhi - Xuất nhập tồn', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0038', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Bổ sung thông tin vào phiếu chỉ định XN: loại mẫu ban đầu, ngày và giờ lấy mẫu, tên nhân viên lấy mẫu, ngày giờ nhận mẫu, tên nhân viên nhận mẫu', 'BVĐK KV Ngã Bảy - Phiếu chỉ định XN', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0039', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Cho đổ KQ chạy nội kiểm của các máy xét nghiệm của hệ thống LIS (có kèm theo ngày, giờ có kết quả biểu đồ Levey-Jennings thể hiện giá trị nội kiểm qua các ngày) để đáp ứng tiêu chí 8.11 của Quyết định 2429/QĐ-BYT ngày 12/6/2017', 'BVĐK KV Ngã Bảy - Nội kiểm LIS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0040', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Yêu cầu thêm mục sử dụng thuốc, csc 2-3 vào APP KCB', 'BVĐK KV Ngã Bảy - APP KCB', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 41-50
('CRC-202604-0041', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Ký số trả bệnh án trên app', 'BVĐK KV Ngã Bảy - Ký số bệnh án app', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0042', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Toa thuốc và giấy ra viện có thêm mã code, có thêm kết quả cls, ....', 'BVĐK KV Ngã Bảy - Toa thuốc mã code', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0043', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh chức năng quản lý công nợ của bệnh nhân', 'Phòng khám Center Lab - Quản lý công nợ', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0044', NULL, NULL, NULL, NULL, 5, 'Tối ưu chức năng báo cáo thu viện phí /hgi_baocaovienphi', 'Hoàn thiện phần mềm - Báo cáo viện phí', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0045', NULL, NULL, NULL, NULL, 5, 'Tối ưu chức năng thẻ kho dược / cmu_thekhoduocchitiet', 'Hoàn thiện phần mềm - Thẻ kho dược', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0046', NULL, NULL, NULL, NULL, 5, 'Tối ưu chức năng chuyển từ có bhyt sang không bhyt', 'Hoàn thiện phần mềm - Chuyển BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0047', NULL, NULL, NULL, NULL, 5, 'Thêm mới chức năng import map động bảng dữ liệu tất cả danh mục', 'Hoàn thiện phần mềm - Import map động', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0048', NULL, NULL, NULL, NULL, 5, 'Ký số toa thuốc ngoại trú', 'Hoàn thiện phần mềm - Ký số toa thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0049', NULL, NULL, NULL, NULL, 5, 'Chức năng xem tổng các giấy tờ tại khám bệnh ngoại trú', 'Hoàn thiện phần mềm - Xem giấy tờ', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0050', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh hóa đơn điện tử thêm hình thức thu hóa đơn điện tử thêm trạng thái gôm lại CLS và thuốc', 'Phòng Khám Care Medic - Hóa đơn điện tử', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 51-60
('CRC-202604-0051', NULL, NULL, NULL, NULL, 2, 'Tách hoặc tắt chuẩn đoán y học cổ truyền ra khỏi icd 10 nghe, hôm này ngày nào cũng có 1 vài ca bệnh có chuẩn đoán y học cổ truyền lẫn vào icd 10', 'Phòng khám Nhơn Ái - Tách YHCT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0052', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh chức năng xuất dược vật tư order by theo STT hoàn tất khám', 'Phòng khám Tâm An - Xuất dược vật tư', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0053', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Yêu cầu quản lý sổ khám sức khoẻ', 'TTYT KV Long Mỹ - Sổ khám sức khỏe', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0054', NULL, NULL, NULL, NULL, 2, 'Bệnh nhân xuất viện có cấp toa 3 ngày, phần toa thuốc cấp hiện phí dưới dòng cấp toa 3 ngày. hiện tại toa thuốc cấp về đang nằm phía trên dòng cấp toa 3 ngày', 'TTYT KV Châu Thành A - Toa 3 ngày', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0055', (SELECT id FROM customers WHERE customer_code = '93004'), NULL, NULL, NULL, 2, 'Cảnh báo và không cho lập kết quả nếu trùng CLS ngoại trú, nội trú (chỉ định CLS, lập kết quả CLS, thực hiện thủ thuật phủ thuật)', 'TTYT KV Phụng Hiệp - Cảnh báo trùng CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0056', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Bổ sung chức năng copy kết quả cận lâm sàng trong bệnh án ngoại trú tại đơn vị thận nhân tạo', 'BVĐK KV Ngã Bảy - Copy kết quả CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0057', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Bổ sung chức năng truy cập liệt kê cận lâm sàng đã cho trong phần bệnh án ngoại trú tại đơn vị thận nhân tạo', 'BVĐK KV Ngã Bảy - Liệt kê CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0058', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Thêm tính năng ghi xác nhận đồng ý phẫu thuật, thủ thuật và gây mê hồi sức với bảng ký (18 - Giấy cam đoan chấp thuận TTPT và GMHS)', 'BVĐK KV Ngã Bảy - Xác nhận phẫu thuật', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0059', (SELECT id FROM customers WHERE customer_code = '93007'), NULL, NULL, NULL, 6, 'Bổ sung chức năng khoá chấm công theo tháng (tương tự như chức năng khoá dữ liệu khám chữa bệnh). Tránh trường hợp tự thêm chấm công ở chức năng cập nhật phẩu thuật thủ thuật', 'BV Sản Nhi - Khóa chấm công', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0060', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Chặn thực hiện nếu chưa chọn máy thực hiện theo LISt mã CDHA', 'BVĐK KV Ngã Bảy - Chặn máy CDHA', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 61-70
('CRC-202604-0061', (SELECT id FROM customers WHERE customer_code = '93016'), NULL, NULL, NULL, 2, 'Thực hiện điều chỉnh hiển thị tất cả các phiếu ký số theo mẫu Chữ ký mẫu, người ký, chức danh', 'BVĐK KV Ngã Bảy - Hiển thị ký số', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0062', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Bổ sung phần thông tin hành chánh ở các trang lẻ của tờ điều trị tổng', 'TTYT KV Long Mỹ - Thông tin hành chánh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0063', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Bổ sung chức năng nhập buồng, giường trên phiếu điều trị, phiếu tường trình phẫu thuật - thủ thuật', 'TTYT KV Long Mỹ - Nhập buồng giường', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0064', (SELECT id FROM customers WHERE customer_code = '93003'), NULL, NULL, NULL, 2, 'Thêm mới chức năng ghi ký hiệu ksk (bỏ ksk lái xe) và làm chức năng báo cáo thống kê', 'TTYT KV Long Mỹ - Ký hiệu KSK', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0065', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh báo cáo xuất kho không theo bác sĩ', 'Phòng khám Center Lab - Báo cáo xuất kho', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0066', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh báo cáo xuất kho theo bác sĩ', 'Phòng khám Center Lab - Báo cáo xuất kho', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0067', NULL, NULL, NULL, NULL, 2, 'Báo cáo chỉ định CLS', 'Phòng khám Center Lab - Báo cáo CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0068', NULL, NULL, NULL, NULL, 2, 'Báo cáo thực hiện CLS', 'Phòng khám Center Lab - Báo cáo CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0069', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Lập tờ chỉ định sinh thiết bổ sung ô nhập thời gian cố định bệnh phầm (không lấy ngày giờ thống như hiện tại)', 'BV Ung bướu CT - Chỉ định sinh thiết', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0070', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Thêm chức năng in lại tờ chỉ định sinh thiết với bệnh nhân đã kết thúc khám', 'BV Ung bướu CT - In chỉ định sinh thiết', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 71-80
('CRC-202604-0071', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Báo cáo doanh thu BV', 'BV Ung bướu CT - Báo cáo doanh thu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0072', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Phần Chẩn đoán lâm sàng ở mặt chỉ định hiển thị tự động theo chẩn đoán chính/phụ sẵn có (cho phép chỉnh sửa)', 'BV Ung bướu CT - Chẩn đoán lâm sàng', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0073', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Thêm cột mã số lame, kết quả vào phần báo cáo GPB, Phần báo cáo chưa có mã số lame, kết quả, chỉ định theo các biểu mẫu đã cung cấp cho công ty VNPT -> hiện khoa Giải phẫu bệnh vẫn phải báo cáo thủ công, rất mất thời gian và dễ sai sót.', 'BV Ung bướu CT - Báo cáo GPB', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0074', NULL, NULL, NULL, NULL, 2, 'Bảng kê dịch vụ CLS', 'BV Tâm Thần CT - Bảng kê CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0075', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Báo cáo hoạt động tháng & kế hoạch tháng', 'BV Ung bướu CT - Báo cáo tháng', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0076', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung mẫu Chấp nhận & In trong chức năng duyệt phiếu lĩnh/trả', 'BV Ung bướu CT - Duyệt phiếu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0077', NULL, NULL, NULL, NULL, 2, 'Hỗ trợ báo cáo CƠ SỞ, GIƯỜNG BỆNH VÀ HOẠT ĐỘNG KHÁM CHỮA BỆNH', 'BV Lao và bệnh Phổi CT - Báo cáo', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0078', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Báo cáo doanh thu phát sinh trong ngày', 'BV Ung bướu CT - Báo cáo doanh thu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0079', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Báo cáo quyết toán thu chi', 'BV Ung bướu CT - Báo cáo thu chi', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0080', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, '1. Chức năng duyệt 4210 cần lọc ra các bệnh nhân không có chi phí. 2. Quản lý đc danh sách trả về điều trị. xem ở đâu được? nếu chưa có thì bổ sung chức năng này. 3. Thống kê được bao nhiêu cas BHYT khám bệnh trong ngày chưa kết thúc', 'BV Ung bướu CT - Duyệt 4210', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 81-90
('CRC-202604-0081', NULL, NULL, NULL, NULL, 2, 'Thêm cảnh báo khi chỉ định thuốc khi bệnh nhân tái khám bác sĩ chỉ định thuốc trùng với thuốc trước đó đã cho và thuốc vẫn đang dùng chưa hết', 'BV Tâm Thần CT - Cảnh báo thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0082', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mở rộng trường Tên Khoản mục trong danh mục /danhmuc/DMC140_Nhom_KT có thể lưu được 500 ký tự', 'BV Ung bướu CT - Mở rộng trường', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0083', NULL, NULL, NULL, NULL, 2, 'Tra cứu xuất nhập tồn => Cần OS để bổ sung thêm các cột tổng sum phía dưới form', 'BV Tâm Thần CT - Xuất nhập tồn', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0084', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chức năng dự trù hàng và đặt hàng => Hiện tại chức năng trên hệ thống chưa sử dụng được (gọi thầu)', 'BV Ung bướu CT - Dự trù hàng', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0085', NULL, NULL, NULL, NULL, 2, 'In phiếu y lệnh thuốc: BV yêu cầu cho chọn được khoảng thời gian để in phiếu', 'BV Tâm Thần CT - In y lệnh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0086', NULL, NULL, NULL, NULL, 2, 'Hiện chưa cảnh báo bệnh nhân BHYT có chỉ định CLS có chênh lệch, chưa đóng tiền nhưng vẫn thực hiện được', 'BV Tâm Thần CT - Cảnh báo BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0087', NULL, NULL, NULL, NULL, 2, 'Theo dõi hàng thầu cần bổ sung thêm cột số lượng còn lại', 'BV Tâm Thần CT - Hàng thầu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0088', NULL, NULL, NULL, NULL, 2, 'Chức năng dụ trù hàng và đặt hàng', 'BV Tâm Thần CT - Dự trù hàng', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0089', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh biên bản kiểm nhập - phần giờ kiểm kê và giờ kết thúc kiểm kê', 'BV Tâm Thần CT - Biên bản kiểm kê', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0090', NULL, NULL, NULL, NULL, 2, 'Chức năng duyệt phiếu yêu cầu, hoàn trả — cần bổ sung tổng (sum) dưới form', 'BV Tâm Thần CT - Duyệt phiếu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 91-100
('CRC-202604-0091', NULL, NULL, NULL, NULL, 2, 'Chức năng duyệt phiếu bù tủ trực, chỉnh lại số lượng duyệt = 0, phần mềm chưa tính lại thành tiền', 'BV Tâm Thần CT - Bù tủ trực', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0092', NULL, NULL, NULL, NULL, 2, 'DsPhieu Chi hoàn ứng', 'PK Hòa Hảo Long Mỹ - Phiếu chi', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0093', NULL, NULL, NULL, NULL, 2, 'DsPhieu Chi trả POS', 'PK Hòa Hảo Long Mỹ - Phiếu chi POS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0094', NULL, NULL, NULL, NULL, 2, 'DsPhieu Chi trả QR Code', 'PK Hòa Hảo Long Mỹ - Phiếu chi QR', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0095', NULL, NULL, NULL, NULL, 2, 'DsPhieu Thu tạm ứng', 'PK Hòa Hảo Long Mỹ - Phiếu thu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0096', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh form chỉ định cls dời cột loại thanh toán mới lên cột đầu tiên', 'PK Hòa Hảo Long Mỹ - Form CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0097', NULL, NULL, NULL, NULL, 2, 'nữ 11', 'PK Hòa Hảo Long Mỹ - nữ 11', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0098', NULL, NULL, NULL, NULL, 2, 'Tự động gửi chỉ định qua BKPacs khi bấm lưu chỉ định mà không cần bấm nút gửi', 'PK Hòa Hảo Long Mỹ - Gửi BKPacs', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0099', NULL, NULL, NULL, NULL, 2, 'Thêm hình thức thanh toán TM/CK trên hóa đơn (hiện tại chỉ có TIENMAT và CHUYENKHOAN)', 'PK Hòa Hảo Long Mỹ - Hình thức thanh toán', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0100', NULL, NULL, NULL, NULL, 2, 'Trải nghiệm vnCare', 'PK Hòa Hảo Long Mỹ - vnCare', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 101-110
('CRC-202604-0101', NULL, NULL, NULL, NULL, 2, 'Phiếu thu/ Đơn thuốc/ Chỉ định in A5 nhưng để giấy ngang như A4', 'PK Hòa Hảo Long Mỹ - In A5', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0102', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh form trả kết quả tăng độ phân giải cao, text box kết luận full hàng không cột', 'PK Hòa Hảo Long Mỹ - Trả kết quả', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0103', NULL, NULL, NULL, NULL, 2, 'Cho phép chọn ảnh cdha khi in kết siêu âm nội soi', 'PK Hòa Hảo Long Mỹ - Ảnh CDHA', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0104', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Thực hiện báo cáo ADR', 'BV Ung bướu CT - Báo cáo ADR', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0105', NULL, NULL, NULL, NULL, 2, 'Màn hình chờ bệnh nhân theo VNVC', 'PK Hòa Hảo Long Mỹ - Màn hình chờ', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0106', NULL, NULL, NULL, NULL, 2, 'Xuất hoá đơn miễn giảm có tồng tiền chi tiết dịch vụ phải miễn giảm bằng tổng tiền miễn giảm của hoá đơn. Cho phép phát hành hoá đơn gộp nhiều phiếu thu miễn giảm', 'PK Hòa Hảo Long Mỹ - Hóa đơn miễn giảm', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0107', NULL, NULL, NULL, NULL, 2, 'Thẻ bhyt hết hạn khi còn đang khám chữa bệnh thì tự map các dvkt sau hạn thẻ bhyt thành dịch vụ chứ không cần chuyển thủ công', 'BV Lao và bệnh Phổi CT - Thẻ BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0108', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh phiếu in PHIẾU THỰC HIỆN Y LỆNH THUỐC', 'BV Tâm Thần CT - Y lệnh thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0109', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chưa lập được phiếu yêu cầu pha chế từ khoa lâm sàng.', 'BV Ung bướu CT - Pha chế', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0110', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chưa lập được phiếu thực hiện pha chế từng loại thuốc của người bệnh.', 'BV Ung bướu CT - Pha chế', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 111-120
('CRC-202604-0111', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chưa xuất được phiếu tổng hợp pha chế thuốc của bệnh nhân trong ngày.', 'BV Ung bướu CT - Pha chế', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0112', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chức năng chống chỉ định ICD và hoạt chất', 'BV Ung bướu CT - Chống chỉ định', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0113', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Yêu cầu danh sách bệnh nhân thu viện phí phải sắp xếp theo thứ tự abc', 'BV Ung bướu CT - Viện phí', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0114', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Không tách hoá đơn khi thu tiền', 'BV Ung bướu CT - Hóa đơn', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0115', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Cảnh báo số ca thực hiện cận lâm sàng/máy trong một ngày', 'BV Ung bướu CT - Cảnh báo CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0116', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Cho phép điều chỉnh Can thiệp điều dưỡng trong phiếu chăm sóc 1, 2-3', 'BV Ung bướu CT - Chăm sóc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0117', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Cho phép thời gian truyền máu được điều chỉnh, do trong thời gian truyền có thể tạm ngưng nên tính tự động có thể dẫn đến sai thời gian', 'BV Ung bướu CT - Truyền máu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0118', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Yêu cầu chức năng Bảng ghi thuốc', 'BV Ung bướu CT - Ghi thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0119', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung danh mục thuốc/vật tư thêm cột ghi chú. Điều chỉnh chức năng kê toa của BS thể hiện thêm cột ghi chú trên lưới cho BS chọn đúng tên', 'BV Ung bướu CT - Danh mục thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0120', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Sơ kết 15 ngày điều trị phần mềm hiện tại chỉ nhắc lần đầu không nhắc lại trong thời gian 15 ngày tiếp theo. Nên chỉnh lại nhắc mỗi 15 ngày.', 'BV Ung bướu CT - Sơ kết', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 121-130
('CRC-202604-0121', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Thống kê được danh sách (mở khóa bệnh án) trả về điều trị chưa kết thúc lại, bộ lọc danh sách bệnh nhân thanh toán BHYT.', 'BV Ung bướu CT - Thống kê', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0122', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Tăng kích cỡ kiểu dữ liệu tên thuốc 1024', 'BV Ung bướu CT - Tên thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0123', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung trường lame để nhập liệu, bổ sung trường số giải phẫu bệnh lên báo cáo thống kê', 'BV Ung bướu CT - Giải phẫu bệnh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0124', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Điều chỉnh mẫu Kết quả giải phẫu bệnh', 'BV Ung bướu CT - Giải phẫu bệnh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0125', NULL, NULL, NULL, NULL, 2, 'Bênh án dài ngày hen phế quản', 'BV Lao và bệnh Phổi CT - Hen phế quản', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0126', NULL, NULL, NULL, NULL, 2, 'Bệnh án dài ngày copd', 'BV Lao và bệnh Phổi CT - COPD', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0127', NULL, NULL, NULL, NULL, 2, 'Báo cáo theo dõi thời gian chờ cấp phát thuốc', 'BV Tâm Thần CT - Cấp phát thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0128', NULL, NULL, NULL, NULL, 2, 'Bổ sung số vào viện trên Phiếu điện tim', 'BV Tâm Thần CT - Điện tim', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0129', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh hiển thị Thuốc mua ngoài đã được lựa chọn trong các phiếu điều trị', 'BV Tâm Thần CT - Thuốc mua ngoài', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0130', NULL, NULL, NULL, NULL, 2, 'Bổ sung cửa sổ cho phép xem toàn bộ quá trình điều trị của người bệnh', 'BV Tâm Thần CT - Quá trình điều trị', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 131-140
('CRC-202604-0131', NULL, NULL, NULL, NULL, 2, 'Bổ sung câu hỏi trắc nghiệm tâm lý trên phần mềm', 'BV Tâm Thần CT - Test tâm lý', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0132', NULL, NULL, NULL, NULL, 2, 'Tách được số liệu báo cáo: BHYT nội trú, ngoại trú; Thu phí nội trú, ngoại trú; Tổng số', 'BV Tâm Thần CT - Báo cáo', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0133', NULL, NULL, NULL, NULL, 2, 'Chỉnh report Giấy báo tử. 1. Chắc năng cấp lập giấy báo tử trên form đã chọn nhưng trên mẫu in chưa hiện thị ở mục lưu ý. 2. Tại mục: Tinh trạng tử vong -> Chọn Trên đường đến CSKCB thì trên mẫu in sẽ tick vào ô Có của mục lưu ý: Tử vong khi đang trên đường đi cấp cứu', 'BV Lao và bệnh Phổi CT - Giấy báo tử', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0134', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung tên bệnh nhân khi thực hiện phiếu chăm sóc cấp 1,2,3. Người dùng phản anh khi thêm phiếu chăm sóc không có dấu hiệu nhận biết đang làm cho bệnh nhân nào', 'BV Ung bướu CT - Phiếu chăm sóc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0135', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh cho phép Phiếu sơ kết phương pháp điều trị lấy được số lượng thuốc', 'BV Tâm Thần CT - Sơ kết', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0136', NULL, NULL, NULL, NULL, 2, 'Khi sao chép phiếu điều trị chưa cảnh báo bác sĩ trùng y lệnh', 'BV Tâm Thần CT - Sao chép phiếu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0137', NULL, NULL, NULL, NULL, 2, 'Sổ lấy mẫu', 'BV Tâm Thần CT - Sổ lấy mẫu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0138', NULL, NULL, NULL, NULL, 2, 'Sổ nhận mẫu', 'BV Tâm Thần CT - Sổ nhận mẫu', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0139', NULL, NULL, NULL, NULL, 2, 'Sổ trả kết quả', 'BV Tâm Thần CT - Sổ trả kết quả', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0140', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'DS bệnh nhân chưa thanh toán là những BN còn nằm trong khoa tổng tiền tạm ứng còn lại là 665tr. Dựa theo bảng tổng thực thu cả năm cắt ngay ngày 31/12 thì chị Oanh sẽ lấy báo cáo từ đầu tháng đến ngày cắt là 31/12, lấy cột Từ tạm ứng cộng cột Tổng chi, sau đó lấy Tổng tiển tạm ứng trừ 2 cái (cột Từ tạm ứng cộng cột Tổng chi) = số tiền tạm ứng của bệnh nhân thì nó không ra đúng 665tr là nó đang bị lệch chỗ đó', 'BV Ung bướu CT - Công nợ', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 141-150
('CRC-202604-0141', NULL, NULL, NULL, NULL, 2, 'Cho phép in số thứ tự CLS sau khi bấm chuyển phòng thực hiện', 'PK Hòa Hảo Long Mỹ - Số thứ tự CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0142', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Hiện tại, khi PACS trả kết quả chụp (bao gồm link ca chụp, thời gian chụp, máy chụp) về HIS, trên HIS tự động chuyển trạng thái sang Đã thực hiện, dẫn đến khóa chức năng nhập kết quả. Yêu cầu điều chỉnh: khi PACS trả kết quả về không tự động chuyển trạng thái sang Đã có kết quả, để vẫn cho phép người dùng nhập kết quả trên HIS.', 'BV Ung bướu CT - PACS kết quả', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0143', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chưa có các mẫu kết quả (~1600 mẫu) gồm chẩn đoán và vi thể.', 'BV Ung bướu CT - Mẫu kết quả', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0144', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Chặn ra viện trước hoặc sau ngày hiện tại, chỉ mở khoá cho tài khoản được phân quyền hoặc Admin', 'BV Ung bướu CT - Chặn ra viện', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0145', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Form sửa mã ICD10 tại Bệnh án chung và Chuyển viện những mã ICD10 có ký tự đặc biệt không lưu lại được. Site: Ung Bướu, Lao Phổi, Tâm Thần', 'BV Ung bướu CT - ICD10', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0146', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: Bổ sung các mẫu phiếu do BV cung cấp (chưa có chức năng chưa có mẫu in). 1. PHIẾU ĐÁNH GIÁ KHẨU PHẦN ĂN 24 GIỜ. 2. PHIẾU ĐÁNH GIÁ TÌNH TRẠNG DINH DƯỠNG THEO PG-SGA. 3. PHIẾU KHÁM VÀ TƯ VẤN DINH DƯỠNG CHO NGƯỜI BỆNH NGOẠI TRÚ. 4. PHIẾU HƯỚNG DẪN CHẾ ĐỘ DINH DƯỠNG CHO NGƯỜI BỆNH NỘI TRÚ', 'BV Ung bướu CT - Mẫu ký số', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0147', NULL, NULL, NULL, NULL, 2, 'Bổ sung Báo cáo chỉ định cận lâm sàng (BÁO CÁO CẬN LÂM SÀNG)', 'BV Tâm Thần CT - Báo cáo CLS', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0148', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: Phiếu theo dõi tại phòng hồi tỉnh. Code: Nội dung điều chỉnh: chưa tìm thấy chức năng và mẫu ký số', 'BV Ung bướu CT - Hồi tỉnh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0149', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: Phiếu theo dõi và hồi sức người bệnh chưa mổ và sau mổ (từ giờ thứ 25 trở đi). Code: Nội dung điều chỉnh: chưa tìm thấy chức năng và mẫu ký số', 'BV Ung bướu CT - Hồi sức', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0150', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Bảng kê BHYT. Code: NGT001_BKCPKCBBHYT_QD6556_DOC_A4. Nội dung điều chỉnh: chưa có reportcode ký số', 'BV Tâm Thần CT - Bảng kê BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 151-160
('CRC-202604-0151', NULL, NULL, NULL, NULL, 2, 'Mẫu báo cáo: Báo cáo quyết toán chi phí khám bệnh, chữa bệnh bảo hiểm y tế. Ký hiệu: 01/BH. Tên đơn vị: CTY TNHH CA.MEDIC CẦN THƠ PHÒNG KHÁM ĐA KHOA HÒA HẢO - LONG MỸ. Mã đơn vị: 92150. Đính kèm file đơn vị cung cấp', 'PK Hòa Hảo Long Mỹ - Báo cáo BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0152', NULL, NULL, NULL, NULL, 2, 'Mẫu báo cáo: Báo cáo quyết toán chi phí khám bệnh, chữa bệnh bảo hiểm y tế. Ký hiệu: 02/BH. Tên đơn vị: CTY TNHH CA.MEDIC CẦN THƠ PHÒNG KHÁM ĐA KHOA HÒA HẢO - LONG MỸ. Mã đơn vị: 92150. Đính kèm file đơn vị cung cấp', 'PK Hòa Hảo Long Mỹ - Báo cáo BHYT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0153', NULL, NULL, NULL, NULL, 2, 'Phần loại bệnh án nội khoa của site https://bvcantho.vncare.vn/ hiện tại đang null(chưa có reportcode) nên khi vào in ấn -> In bệnh án chi tiết không có report code để in nên lỗi. Menu: Điều trị nội trú->In ấn->In bệnh án chi tiết', 'BV Lao và bệnh Phổi CT - Bệnh án nội khoa', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0154', NULL, NULL, NULL, NULL, 2, 'Tạo tham số chặn khi có phát sinh chi phí chênh lệch', 'PK Hòa Hảo Long Mỹ - Chênh lệch', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0155', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, '1. BC SD HC CTO. 2. BC SD VT CTO. 3. BC XNT BV CTO. 4. BC KIỂM KÊ THEO TT22 PL8. 5. BB HÓA ĐƠN CTO HC-VT. 6. QUẢN LÝ VÀ IN BB KIỂM NHẬP HC-VT => Bổ sung trang in', 'BV Ung bướu CT - Báo cáo', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0156', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Điều chỉnh các báo cáo NXT và báo cáo kiểm nhập hóa đơn theo nội dung cuộc họp ngày 16/03/2026', 'BV Ung bướu CT - Báo cáo NXT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0157', NULL, NULL, NULL, NULL, 2, 'Bổ sung thêm mẫu xuất khác', 'BV Lao và bệnh Phổi CT - Mẫu xuất', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0158', NULL, NULL, NULL, NULL, 2, 'Bổ sung tool check CCCD gắn chip theo thiết bị của BV Lao', 'BV Lao và bệnh Phổi CT - CCCD chip', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0159', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu theo dõi điều trị. Code: NTU020_TODIEUTRI_39BV01_QD4069_A4_ONE, NTU020_TODIEUTRI_39BV01_QD4069_A4_ALL, NTU020_TODIEUTRI_39BV01_QD4069_A4_MULTI. Nội dung điều chỉnh: 1. In hoa tên bệnh viện. 2. Làm ký hiệu tròn, vuông, tam giác của nhóm thuốc kháng viêm, kháng sinh, an thần như mẫu in thường', 'BV Lao và bệnh Phổi CT - Theo dõi điều trị', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0160', NULL, NULL, NULL, NULL, 2, 'Chọn công khám thì sẽ đính kèm DVKT. Tạo tham số: - BHYT: Nếu bệnh nhân có BHYT thì sẽ đính kèm DVKT, bệnh nhân thu phí thì không đính kèm. Nếu DVKT không có giá bhyt thì lấy giá viện phí - VP: ngược lại với BHYT - Tắt. Khi chuyển phòng: - DVKT đính kèm chưa thực hiện -> xóa bỏ DVKT đó - DVKT đính kèm đã thực hiện -> giữ lại không xóa', 'PK Hòa Hảo Long Mỹ - Công khám', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 161-170
('CRC-202604-0161', NULL, NULL, NULL, NULL, 2, 'Khi chọn công khám ban đầu đã tính tiền chênh lệch, khi chuyển phòng vẫn còn tính thêm một lần tiền chênh lệch nữa', 'PK Hòa Hảo Long Mỹ - Chênh lệch', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0162', NULL, NULL, NULL, NULL, 2, 'Chức năng xem lại bệnh án chi tiết đối với bệnh nhân đã xuất viện', 'BV Lao và bệnh Phổi CT - Bệnh án', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0163', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Triển khai Giải pháp thanh toán không dùng tiền mặt tại Bệnh viện Ung Bướu TP Cần Thơ cùng đối tác Ngân hàng VietinBank đính kèm file', 'BV Ung bướu CT - Thanh toán', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0164', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Hiện tại, các đơn vị BVUB CS1,2 và CS3 đang sử dụng chung một site hóa đơn. Điều này dẫn đến khi phát hành hóa đơn tại cơ sở 3 bị trùng key hóa đơn với các hóa đơn đã phát hành trước đó của CS1 và CS2. Kính nhờ anh/chị xem xét điều chỉnh lại cơ chế sinh key hóa đơn theo cấu trúc sau: Company ID + Mã bệnh án + Mã phiếu thu + Chuỗi số thứ tự tăng dần Đảm bảo mỗi key là duy nhất trong trường hợp nhiều đơn vị cùng sử dụng chung một site hóa đơn.', 'BV Ung bướu CT - Key hóa đơn', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0165', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Giấy chứng nhận nghỉ việc hưởng bảo hiểm xã hội. Code: RPT_GIAYNGHI_BHXH. Nội dung điều chỉnh: 1. Chưa lấy được số seri. 2. Chưa lấy được thông tin ký số người hành nghệ KB, CB. 3. Dư ký tự BS.', 'BV Lao và bệnh Phổi CT - Giấy nghỉ việc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0166', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Đơn thuốc BHYT. Code: NGT006_DONTHUOC_17DBV01_TT052016_A5. Nội dung điều chỉnh: 1. Đổi logo thành BV Phổi. 2. Chưa load đc CCCD bệnh nhân. 3. Chưa load được thông tin thân nhân bệnh nhân. 4. Mã đơn thuốc lấy dữ liệu chưa đúng (đang load số phiếu thuốc)', 'BV Lao và bệnh Phổi CT - Đơn thuốc', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0167', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Bệnh án Nội khoa. Code: BAN_NK01. Nội dung điều chỉnh: Chưa có mẫu ký số. Lỗi: Đã có lỗi xảy ra khi đọc file template', 'BV Lao và bệnh Phổi CT - Bệnh án', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0168', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu khai thác tiền sử dị ứng. Code: NTU_PHIEU_KHAITHAC_TIENSU_DIUNG. Nội dung điều chỉnh: Chưa có mẫu ký số.', 'BV Lao và bệnh Phổi CT - Tiền sử dị ứng', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0169', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Bảng kê BHYT. Code: NGT001_BKCPKCBBHYT_QD6556_A4. Nội dung điều chỉnh: Chưa có chức năng ký và mẫu ký số.', 'BV Lao và bệnh Phổi CT - Bảng kê', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0170', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung mẫu phiếu xuất khác ra file excel theo file mẫu import nhập hóa đơn', 'BV Ung bướu CT - Phiếu xuất', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 171-180
('CRC-202604-0171', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: Toa thuốc nghiện. Code: NGT013_DONTHUOCGAYNGHIEN_TT052016_A5. Nội dung điều chỉnh: 1. Điểu chỉnh lại theo cấu trúc toa thuốc nghiện củao TT26. 2. Lấy thông tin người ký số', 'BV Ung bướu CT - Toa nghiện', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0172', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Biên bản hội chẩn (Sổ biên bản hội chẩn). Code: NTU045_TRICHSOBIENBANHOICHAN_40BV01_QD4069_A4. Nội dung điều chỉnh: chưa có chức năng ký số và mẫu ký số', 'BV Lao và bệnh Phổi CT - Hội chẩn', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0173', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Bảng kiểm an toàn phẩu thuật. Code: RPT_BANGKIEM_ANTOANPTTT. Nội dung điều chỉnh: lỗi tạo phiếu và ký số (Mã lỗi = 500)', 'BV Lao và bệnh Phổi CT - An toàn PT', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0174', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu khám tiền mê. Code: Nội dung điều chỉnh: chưa có chức năng ký số và mẫu ký số', 'BV Lao và bệnh Phổi CT - Khám tiền mê', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0175', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu theo dõi người bệnh sau khi mổ (trong 24 giờ đầu). Code: PHIEU_THEODOI_SAUMO_ALL. Nội dung điều chỉnh: chưa có mẫu ký số', 'BV Lao và bệnh Phổi CT - Sau mổ', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0176', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu theo dõi tại phòng hồi tỉnh. Code: Nội dung điều chỉnh: chưa có chức năng ký số và mẫu ký số', 'BV Lao và bệnh Phổi CT - Hồi tỉnh', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0177', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu đánh giá trước khi cho người bệnh ra khỏi phòng hồi tỉnh. Code: Nội dung điều chỉnh: chưa có chức năng ký số và mẫu ký số', 'BV Lao và bệnh Phổi CT - Đánh giá', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0178', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu theo dõi và hồi sức người bệnh chưa mổ và sau mổ (từ giờ thứ 25 trở đi). Code: Nội dung điều chỉnh: chưa có chức năng ký số và mẫu ký số', 'BV Lao và bệnh Phổi CT - Hồi sức', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0179', NULL, NULL, NULL, NULL, 2, 'Điều chỉnh thông báo các lỗi về thời gian trong chức năng lưu của CĐHA', 'PK Hòa Hảo Long Mỹ - CĐHA', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0180', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bảng kê chi phí cho phép hiển thị thuốc giá 0đ', 'BV Ung bướu CT - Bảng kê', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 181-190
('CRC-202604-0181', NULL, NULL, NULL, NULL, 2, 'Gọi số chỉ đến số lớn nhất từ máy bắt số kiosk', 'PK Hòa Hảo Long Mỹ - Kiosk', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0182', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bảng kê chi phí theo quyết định 697', 'BV Ung bướu CT - QĐ 697', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0183', NULL, NULL, NULL, NULL, 2, 'Bảng kê chi phí theo quyết định 697', 'BV Tâm Thần CT - QĐ 697', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0184', NULL, NULL, NULL, NULL, 2, 'Bảng kê chi phí theo quyết định 697', 'BV Lao và bệnh Phổi CT - QĐ 697', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0185', NULL, NULL, NULL, NULL, 2, 'Bảng kê chi phí theo quyết định 697', 'PK Hòa Hảo Long Mỹ - QĐ 697', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0186', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Bổ sung ICD 9 và cho phép cập nhật DVKT vào ICD9', 'BV Ung bướu CT - ICD9', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0187', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu in: In bệnh lịch. Code: BENHLICH_A4_951. Nội dung điều chỉnh: 1. Tên bệnh nhân hiểm thị không đầy đủ. 2. Tên chẩn đoán hiển thị không đầy đủ. 3. Chưa hiển thị tên khoa. Chức năng: Ngoại trú -> Khám bệnh->chọn bệnh nhân chuột phải -> IN bệnh lịch', 'BV Ung bướu CT - Bệnh lịch', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0188', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: GIẤY CUNG CẤP THÔNG TIN VÀ CAM KẾT CHUNG VỀ NHẬP VIỆN NỘI TRÚ. Code: PHIEUCAMKETNHAPVIENNOITRU_40BV2_TT32. Nội dung điều chỉnh: Bn này trẻ dưới 6 tuổi là 68 tháng chứ hong phải 68 tuổi nha, anh xem chỉnh lại chỗ này thên chữ tháng => BN dưới 6 tuổi thêm chữ tháng như tờ điều trị', 'BV Ung bướu CT - Giấy cam kết', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0189', NULL, NULL, NULL, NULL, 2, 'Bổ sung mẫu ký số đơn thuốc, phiếu chỉ định CLS, bảng kê', 'PK Hòa Hảo Long Mỹ - Mẫu ký số', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0190', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Các thang đánh giá tâm lý (KẾT QUẢ TEST TÂM LÝ). Code: Nội dung điều chỉnh: chưa có mẫu ký số', 'BV Tâm Thần CT - Test tâm lý', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
-- STT 191-197
('CRC-202604-0191', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu đo lưu huyết não. Code: Nội dung điều chỉnh: chưa có mẫu ký số', 'BV Tâm Thần CT - Lưu huyết não', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0192', NULL, NULL, NULL, NULL, 2, 'Mẫu ký số: Phiếu chuyển tuyến về TTYT tại địa phương. Code: RPT_PHIEUCHUYEN_VE_TTYT. Nội dung điều chỉnh: chưa có mẫu ký số', 'BV Lao và bệnh Phổi CT - Chuyển tuyến', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0193', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: THẺ CẢNH BÁO PHẢN ỨNG CÓ HẠI CỦA BỆNH NHÂN. Code: Nội dung điều chỉnh: chưa có mẫu ký số (mẫu mới). Áp dụng cho Ngoại trú, Điều trị ngoại trú, Nội trú', 'BV Ung bướu CT - Thẻ cảnh báo', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0194', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Mẫu ký số: BÁO CÁO PHẢN ỨNG CÓ HẠI CỦA THUỐC. Code: Nội dung điều chỉnh: chưa có mẫu ký số (mẫu mới). Note: góc trên bên phải 1. Nơi báo cáo là tên bệnh viện (Mặc định), 2. Mã số báo cáo của đơn vị để cho Dược tự nhập vào, 3. Mã số báo cáo (do trung tâm quốc gia quản lý) thì mình để trống', 'BV Ung bướu CT - Báo cáo ADR', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0195', NULL, NULL, NULL, NULL, 2, 'Yêu cầu từ Khoa khám bệnh. Bổ sung chức năng làm giấy Tóm tắt hồ sơ bệnh án tương tư như Nội trú và điều trị ngoại trú', NULL, 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0196', (SELECT id FROM customers WHERE customer_code = '93999'), NULL, NULL, NULL, 1, 'Điều chỉnh Biên bản hóa đơn tháng CTO bổ sung gr trên mẫu in', 'BV Ung bướu CT - Biên bản', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW()),
('CRC-202604-0197', NULL, NULL, NULL, NULL, 2, 'Mẫu in: Giấy chuyển tuyến. Code: NGT003_GIAYCHUYENTUYEN_TT14_A4. Nội dung điều chỉnh: Khi chọn lý do: Phù hợp với điều kiện chuyển tuyến -> Trên giấy chuyển tuyến phải đánh dấu X vào ô 1.B', 'BV Tâm Thần CT - Giấy chuyển tuyến', 2, 'Kênh khác', 1, 'new_intake', 10, 9, 9, NOW(), NOW());

-- Hiển thị kết quả
SELECT 'Import completed' AS status, COUNT(*) AS total_imported
FROM customer_request_cases
WHERE request_code LIKE 'CRC-202604-%';
