import React, { useEffect, useRef, useState } from 'react';
import { Customer } from '../../types';
import {
  CUSTOMER_SECTOR_OPTIONS,
  HEALTHCARE_FACILITY_TYPE_OPTIONS,
  facilityTypeSupportsBedCapacity,
  inferCustomerSector,
  inferHealthcareFacilityType,
  normalizeCustomerSectorValue,
  normalizeHealthcareFacilityTypeValue,
  resolveHealthcareFacilityType,
} from '../../utils/customerClassification';
import { FormInput, ModalWrapper } from './shared';

type CustomerFormField =
  | 'customer_code'
  | 'customer_name'
  | 'tax_code'
  | 'address'
  | 'customer_sector'
  | 'healthcare_facility_type'
  | 'bed_capacity';

type CustomerFormErrors = Partial<Record<CustomerFormField, string>>;

const CUSTOMER_FIELD_ORDER: CustomerFormField[] = [
  'customer_code',
  'customer_name',
  'tax_code',
  'address',
  'customer_sector',
  'healthcare_facility_type',
  'bed_capacity',
];

export interface CustomerFormModalProps {
  type: 'ADD' | 'EDIT';
  data?: Customer | null;
  onClose: () => void;
  onSave: (data: Partial<Customer>) => Promise<void>;
}

export const validateCustomerForm = (formData: Partial<Customer>): CustomerFormErrors => {
  const errors: CustomerFormErrors = {};
  const customerCode = String(formData.customer_code || '').trim();
  const customerName = String(formData.customer_name || '').trim();
  const taxCode = String(formData.tax_code || '').trim();
  const customerSector = String(formData.customer_sector || 'OTHER').trim().toUpperCase();
  const facilityType = formData.healthcare_facility_type
    ? normalizeHealthcareFacilityTypeValue(
      formData.healthcare_facility_type,
      inferHealthcareFacilityType(formData.customer_name || ''),
    )
    : null;
  const hasBedCapacity = formData.bed_capacity !== null && formData.bed_capacity !== undefined && String(formData.bed_capacity).trim() !== '';

  if (customerCode.length > 100) {
    errors.customer_code = 'Mã khách hàng tối đa 100 ký tự';
  }

  if (!customerName) {
    errors.customer_name = 'Vui lòng nhập Tên khách hàng';
  } else if (customerName.length > 255) {
    errors.customer_name = 'Tên khách hàng tối đa 255 ký tự';
  }

  if (taxCode.length > 100) {
    errors.tax_code = 'Mã số thuế tối đa 100 ký tự';
  }

  if (customerSector === 'HEALTHCARE' && !facilityType) {
    errors.healthcare_facility_type = 'Vui lòng chọn loại hình cơ sở y tế.';
  }

  if (customerSector === 'HEALTHCARE' && facilityTypeSupportsBedCapacity(facilityType, formData.customer_name || '') && hasBedCapacity) {
    const bedCapacity = Number(formData.bed_capacity);
    if (!Number.isInteger(bedCapacity) || bedCapacity < 0) {
      errors.bed_capacity = 'Quy mô giường bệnh phải là số nguyên không âm.';
    } else if (bedCapacity > 1000000) {
      errors.bed_capacity = 'Quy mô giường bệnh không được vượt quá 1.000.000.';
    }
  }

  return errors;
};

export const CustomerFormModal: React.FC<CustomerFormModalProps> = ({ type, data, onClose, onSave }) => {
  const initialCustomerName = data?.customer_name || data?.company_name || '';
  const initialCustomerCode = data?.customer_code || '';
  const initialCustomerSector = normalizeCustomerSectorValue(
    data?.customer_sector,
    inferCustomerSector(initialCustomerName),
  );
  const initialHealthcareFacilityType = initialCustomerSector === 'HEALTHCARE'
    ? resolveHealthcareFacilityType({
      healthcare_facility_type: data?.healthcare_facility_type,
      customer_name: initialCustomerName,
      company_name: data?.company_name,
    })
    : null;
  const [formData, setFormData] = useState<Partial<Customer>>({
    customer_code: initialCustomerCode,
    customer_name: initialCustomerName,
    tax_code: data?.tax_code || '',
    address: data?.address || '',
    customer_sector: initialCustomerSector,
    healthcare_facility_type: initialHealthcareFacilityType,
    bed_capacity: data?.bed_capacity ?? null,
    uuid: data?.uuid || '',
  });
  const [errors, setErrors] = useState<CustomerFormErrors>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [customerSectorTouched, setCustomerSectorTouched] = useState(Boolean(data?.customer_sector));
  const isMountedRef = useRef(true);
  const isExistingAutoGeneratedCode = Boolean(data?.customer_code_auto_generated)
    && String(formData.customer_code || '').trim() === initialCustomerCode;

  useEffect(() => {
    isMountedRef.current = true;
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  useEffect(() => {
    if (customerSectorTouched) {
      return;
    }

    const inferredSector = inferCustomerSector(formData.customer_name || '');
    setFormData((previous) => {
      const currentSector = String(previous.customer_sector || 'OTHER').toUpperCase();
      if (currentSector === inferredSector) {
        return previous;
      }

      return {
        ...previous,
        customer_sector: inferredSector,
        healthcare_facility_type: inferredSector === 'HEALTHCARE'
          ? previous.healthcare_facility_type ?? inferHealthcareFacilityType(previous.customer_name || '')
          : null,
        bed_capacity:
          inferredSector === 'HEALTHCARE' && facilityTypeSupportsBedCapacity(previous.healthcare_facility_type, previous.customer_name || '')
            ? previous.bed_capacity ?? null
            : null,
      };
    });
  }, [customerSectorTouched, formData.customer_name]);

  const clearFieldError = (field: CustomerFormField) => {
    setErrors((previous) => {
      if (!previous[field]) {
        return previous;
      }
      const next = { ...previous };
      delete next[field];
      return next;
    });
  };

  const focusField = (field: CustomerFormField) => {
    if (typeof document === 'undefined') {
      return;
    }

    const selector = `[data-customer-field="${field}"] input, [data-customer-field="${field}"] textarea`;
    const element = document.querySelector(selector) as HTMLElement | null;
    if (!element) {
      return;
    }

    element.scrollIntoView({ behavior: 'smooth', block: 'center' });
    if (typeof element.focus === 'function') {
      element.focus();
    }
  };

  const handleSubmit = async () => {
    const normalizedCustomerSector = String(formData.customer_sector || 'OTHER').trim().toUpperCase();
    const bedCapacityValue = formData.bed_capacity;
    const customerSector = normalizeCustomerSectorValue(normalizedCustomerSector);
    const healthcareFacilityType = customerSector === 'HEALTHCARE'
      ? normalizeHealthcareFacilityTypeValue(
        formData.healthcare_facility_type,
        inferHealthcareFacilityType(formData.customer_name || ''),
      )
      : null;
    const normalizedData: Partial<Customer> = {
      ...formData,
      customer_code: String(formData.customer_code || '').trim(),
      customer_name: String(formData.customer_name || '').trim(),
      tax_code: String(formData.tax_code || '').trim(),
      address: String(formData.address || ''),
      customer_sector: customerSector,
      healthcare_facility_type: healthcareFacilityType,
      bed_capacity:
        customerSector === 'HEALTHCARE'
        && facilityTypeSupportsBedCapacity(healthcareFacilityType, formData.customer_name || '')
        && bedCapacityValue !== null
        && bedCapacityValue !== undefined
        && String(bedCapacityValue).trim() !== ''
          ? Number(bedCapacityValue)
          : null,
    };

    const validationErrors = validateCustomerForm(normalizedData);
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      const firstInvalidField = CUSTOMER_FIELD_ORDER.find((field) => validationErrors[field]);
      if (firstInvalidField) {
        requestAnimationFrame(() => focusField(firstInvalidField));
      }
      return;
    }

    setIsSubmitting(true);
    try {
      await onSave(normalizedData);
    } catch {
      // Parent shows the toast, modal stays open for continued editing.
    } finally {
      if (isMountedRef.current) {
        setIsSubmitting(false);
      }
    }
  };

  return (
    <ModalWrapper
      onClose={onClose}
      title={type === 'ADD' ? 'Thêm khách hàng' : 'Cập nhật khách hàng'}
      icon="domain"
      width="max-w-3xl"
      disableClose={isSubmitting}
    >
      <div className="px-5 py-4 space-y-4">
        <div className="rounded-lg border border-gray-200 bg-white p-4 space-y-4">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="text-sm font-semibold text-slate-800">Thông tin cơ bản</p>
            </div>
            <span className="material-symbols-outlined text-slate-300">badge</span>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div data-customer-field="customer_code">
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <label className="text-xs font-semibold text-neutral">Mã khách hàng</label>
                  {isExistingAutoGeneratedCode ? (
                    <span className="inline-flex items-center rounded-full bg-blue-50 px-2 py-0.5 text-[11px] font-semibold text-blue-700">
                      Tự sinh
                    </span>
                  ) : null}
                </div>
                <input
                  type="text"
                  value={formData.customer_code || ''}
                  onChange={(e: any) => {
                    setFormData({ ...formData, customer_code: e.target.value });
                    clearFieldError('customer_code');
                  }}
                  placeholder="KH001"
                  title={String(formData.customer_code || '')}
                  className={`w-full h-8 px-3 rounded border bg-white text-xs text-slate-900 focus:ring-1 focus:ring-primary/30 focus:border-primary outline-none transition-all placeholder:text-slate-400 ${errors.customer_code ? 'border-error ring-1 ring-error/30' : 'border-slate-300'}`}
                />
                <p className="text-xs text-slate-500">Để trống hệ thống tự sinh theo Tên khách hàng.</p>
                {errors.customer_code ? <p className="text-[11px] text-error mt-0.5">{errors.customer_code}</p> : null}
              </div>
            </div>
            <div data-customer-field="customer_name">
              <FormInput
                label="Tên khách hàng"
                value={formData.customer_name}
                onChange={(e: any) => {
                  setFormData({ ...formData, customer_name: e.target.value });
                  clearFieldError('customer_name');
                }}
                placeholder="Tên khách hàng"
                required
                error={errors.customer_name}
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div data-customer-field="tax_code">
              <FormInput
                label="Mã số thuế"
                value={formData.tax_code}
                onChange={(e: any) => {
                  setFormData({ ...formData, tax_code: e.target.value });
                  clearFieldError('tax_code');
                }}
                placeholder="010xxxxxx"
                error={errors.tax_code}
              />
            </div>
            <div data-customer-field="address">
              <FormInput
                label="Địa chỉ"
                value={formData.address}
                onChange={(e: any) => {
                  setFormData({ ...formData, address: e.target.value });
                  clearFieldError('address');
                }}
                placeholder="Địa chỉ khách hàng"
                error={errors.address}
              />
            </div>
          </div>
        </div>

        <div data-customer-field="customer_sector" className="space-y-3 rounded-lg border border-gray-200 bg-white p-4">
          <div className="flex items-start justify-between gap-3">
            <div>
              <label className="text-sm font-semibold text-slate-700">Nhóm khách hàng</label>
            </div>
            <span className="material-symbols-outlined text-slate-300">category</span>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            {CUSTOMER_SECTOR_OPTIONS.map((option) => {
              const isActive = String(formData.customer_sector || 'OTHER') === option.value;
              return (
                <label
                  key={option.value}
                  className={`flex cursor-pointer items-start gap-3 rounded-xl border px-4 py-3 transition-all ${
                    isActive
                      ? 'border-blue-200 bg-blue-50 shadow-sm shadow-blue-100'
                      : 'border-slate-200 bg-white hover:border-slate-300'
                  }`}
                >
                  <input
                    type="radio"
                    name="customer_sector"
                    value={option.value}
                    checked={isActive}
                    onChange={(event) => {
                      const nextValue = event.target.value as Customer['customer_sector'];
                      setCustomerSectorTouched(true);
                      setFormData((previous) => ({
                        ...previous,
                        customer_sector: nextValue,
                        healthcare_facility_type: nextValue === 'HEALTHCARE'
                          ? previous.healthcare_facility_type ?? inferHealthcareFacilityType(previous.customer_name || '')
                          : null,
                        bed_capacity:
                          nextValue === 'HEALTHCARE' && facilityTypeSupportsBedCapacity(previous.healthcare_facility_type, previous.customer_name || '')
                            ? previous.bed_capacity ?? null
                            : null,
                      }));
                      clearFieldError('customer_sector');
                      clearFieldError('healthcare_facility_type');
                      clearFieldError('bed_capacity');
                    }}
                    className="mt-0.5 h-4 w-4 accent-blue-600"
                  />
                  <div>
                    <div className="text-sm font-semibold text-slate-800">{option.label}</div>
                  </div>
                </label>
              );
            })}
          </div>
        </div>

        {String(formData.customer_sector || 'OTHER') === 'HEALTHCARE' && (
          <div className="space-y-4 rounded-lg border border-sky-100 bg-sky-50/60 p-4">
            <div data-customer-field="healthcare_facility_type" className="space-y-3">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <label className="text-sm font-semibold text-slate-700">
                    Loại hình cơ sở y tế <span className="text-red-500">*</span>
                  </label>
                </div>
                <span className="material-symbols-outlined text-sky-300">local_hospital</span>
              </div>
              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                {HEALTHCARE_FACILITY_TYPE_OPTIONS.map((option) => {
                  const isActive = normalizeHealthcareFacilityTypeValue(
                    formData.healthcare_facility_type,
                    inferHealthcareFacilityType(formData.customer_name || ''),
                  ) === option.value;
                  return (
                    <label
                      key={option.value}
                      className={`flex cursor-pointer items-start gap-3 rounded-xl border px-4 py-3 transition-all ${
                        isActive
                          ? 'border-blue-200 bg-white shadow-sm shadow-blue-100'
                          : 'border-slate-200 bg-white/90 hover:border-slate-300'
                      }`}
                    >
                      <input
                        type="radio"
                        name="healthcare_facility_type"
                        value={option.value}
                        checked={isActive}
                        onChange={(event) => {
                          const nextValue = event.target.value as Customer['healthcare_facility_type'];
                          setFormData((previous) => ({
                            ...previous,
                            healthcare_facility_type: nextValue,
                            bed_capacity: facilityTypeSupportsBedCapacity(nextValue, previous.customer_name || '')
                              ? previous.bed_capacity ?? null
                              : null,
                          }));
                          clearFieldError('healthcare_facility_type');
                          clearFieldError('bed_capacity');
                        }}
                        className="mt-0.5 h-4 w-4 accent-blue-600"
                      />
                      <div>
                        <div className="text-sm font-semibold text-slate-800">{option.label}</div>
                      </div>
                    </label>
                  );
                })}
              </div>
              {errors.healthcare_facility_type ? <p className="text-xs text-red-500">{errors.healthcare_facility_type}</p> : null}
            </div>

            {facilityTypeSupportsBedCapacity(formData.healthcare_facility_type, formData.customer_name || '') && (
              <div data-customer-field="bed_capacity" className="max-w-xs rounded-lg border border-sky-100 bg-white p-4">
                <FormInput
                  label="Quy mô giường bệnh"
                  value={formData.bed_capacity ?? ''}
                  type="number"
                  min="0"
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                    const rawValue = String(e.target.value || '').replace(/\D/g, '');
                    setFormData((previous) => ({
                      ...previous,
                      bed_capacity: rawValue === '' ? null : Number(rawValue),
                    }));
                    clearFieldError('bed_capacity');
                  }}
                  placeholder="Ví dụ: 300"
                  error={errors.bed_capacity}
                />
              </div>
            )}
          </div>
        )}
      </div>
      <div className="flex items-center justify-end gap-3 border-t border-gray-200 bg-gray-50 px-5 py-4">
        <button
          onClick={onClose}
          disabled={isSubmitting}
          className="inline-flex h-11 min-w-[128px] items-center justify-center rounded-lg border border-gray-300 px-4 text-sm font-medium text-slate-700 hover:bg-white disabled:cursor-not-allowed disabled:opacity-60"
        >
          Hủy
        </button>
        <button
          onClick={handleSubmit}
          disabled={isSubmitting}
          className="inline-flex h-11 min-w-[128px] items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60"
        >
          <span
            aria-hidden="true"
            className={`material-symbols-outlined text-lg ${isSubmitting ? 'animate-spin' : ''}`}
          >
            {isSubmitting ? 'progress_activity' : 'check'}
          </span>
          {isSubmitting ? 'Đang lưu...' : 'Lưu'}
        </button>
      </div>
    </ModalWrapper>
  );
};
