SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `product_quotations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `customer_id` bigint unsigned DEFAULT NULL,
  `recipient_name` varchar(255) NOT NULL,
  `sender_city` varchar(120) DEFAULT NULL,
  `quote_date` date DEFAULT NULL,
  `scope_summary` text,
  `vat_rate` decimal(5,2) DEFAULT '10.00',
  `validity_days` smallint unsigned NOT NULL DEFAULT '90',
  `notes_text` text,
  `contact_line` text,
  `closing_message` text,
  `signatory_title` varchar(255) DEFAULT NULL,
  `signatory_unit` varchar(255) DEFAULT NULL,
  `signatory_name` varchar(255) DEFAULT NULL,
  `subtotal` decimal(18,2) NOT NULL DEFAULT '0.00',
  `vat_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_in_words` text,
  `uses_multi_vat_template` tinyint(1) NOT NULL DEFAULT '0',
  `content_hash` varchar(64) DEFAULT NULL,
  `latest_version_no` int unsigned NOT NULL DEFAULT '0',
  `last_printed_at` timestamp NULL DEFAULT NULL,
  `last_printed_by` bigint unsigned DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'DRAFT',
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_quotations_uuid_unique` (`uuid`),
  KEY `idx_product_quotations_status_updated` (`status`,`updated_at`),
  KEY `idx_product_quotations_customer_created` (`customer_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `product_quotation_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `quotation_id` bigint unsigned NOT NULL,
  `sort_order` int unsigned NOT NULL DEFAULT '0',
  `product_id` bigint unsigned DEFAULT NULL,
  `product_name` varchar(500) NOT NULL,
  `unit` varchar(100) DEFAULT NULL,
  `quantity` decimal(18,2) NOT NULL DEFAULT '0.00',
  `unit_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `vat_rate` decimal(5,2) DEFAULT NULL,
  `vat_amount` decimal(18,2) DEFAULT NULL,
  `line_total` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_with_vat` decimal(18,2) DEFAULT NULL,
  `note` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_product_quotation_items_parent_sort` (`quotation_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `product_quotation_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `quotation_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `template_key` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `filename` varchar(255) DEFAULT NULL,
  `quote_date` date NOT NULL,
  `recipient_name` varchar(255) NOT NULL,
  `sender_city` varchar(120) DEFAULT NULL,
  `scope_summary` text,
  `vat_rate` decimal(5,2) DEFAULT NULL,
  `validity_days` smallint unsigned NOT NULL DEFAULT '90',
  `notes_text` text,
  `contact_line` text,
  `closing_message` text,
  `signatory_title` varchar(255) DEFAULT NULL,
  `signatory_unit` varchar(255) DEFAULT NULL,
  `signatory_name` varchar(255) DEFAULT NULL,
  `subtotal` decimal(18,2) NOT NULL DEFAULT '0.00',
  `vat_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_amount` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_in_words` text,
  `uses_multi_vat_template` tinyint(1) NOT NULL DEFAULT '0',
  `content_hash` varchar(64) DEFAULT NULL,
  `printed_at` timestamp NULL DEFAULT NULL,
  `printed_by` bigint unsigned DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_product_quotation_versions_parent_version` (`quotation_id`,`version_no`),
  KEY `idx_product_quotation_versions_parent_printed` (`quotation_id`,`printed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `product_quotation_version_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `version_id` bigint unsigned NOT NULL,
  `sort_order` int unsigned NOT NULL DEFAULT '0',
  `product_id` bigint unsigned DEFAULT NULL,
  `product_name` varchar(500) NOT NULL,
  `unit` varchar(100) DEFAULT NULL,
  `quantity` decimal(18,2) NOT NULL DEFAULT '0.00',
  `unit_price` decimal(18,2) NOT NULL DEFAULT '0.00',
  `vat_rate` decimal(5,2) DEFAULT NULL,
  `vat_amount` decimal(18,2) DEFAULT NULL,
  `line_total` decimal(18,2) NOT NULL DEFAULT '0.00',
  `total_with_vat` decimal(18,2) DEFAULT NULL,
  `note` text,
  PRIMARY KEY (`id`),
  KEY `idx_product_quotation_version_items_parent_sort` (`version_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `product_quotation_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `quotation_id` bigint unsigned NOT NULL,
  `version_id` bigint unsigned DEFAULT NULL,
  `version_no` int unsigned DEFAULT NULL,
  `event_type` varchar(50) NOT NULL,
  `event_status` varchar(20) DEFAULT NULL,
  `template_key` varchar(40) DEFAULT NULL,
  `filename` varchar(255) DEFAULT NULL,
  `content_hash` varchar(64) DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_product_quotation_events_parent_created` (`quotation_id`,`created_at`),
  KEY `idx_product_quotation_events_version_created` (`version_id`,`created_at`),
  KEY `idx_product_quotation_events_type_created` (`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
